services:
  puppeteer-app:
    image: puppeteer-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    cap_add:
      - SYS_ADMIN
    init: true
